# PRODUCTION BUILD
# Stage 1: Build React client
FROM node:lts-alpine as builder

# Working Directory
RUN mkdir -p /usr/app/client
WORKDIR /usr/app/client

# Install dependencies
COPY package*.json ./
RUN npm ci

# copy local files to app folder
COPY . .
# Build
RUN npm run build

# Stage 2: Build Nginx Server
FROM nginx:stable-alpine

# React app의 build 결과물을 nginx가 serve할 수 있도록 copy
COPY --from=builder /usr/app/client/build /usr/share/nginx/html

CMD ["nginx", "-g", "daemon off;"]