FROM node:lts-alpine

# Create App Directory
RUN mkdir -p /usr/app/client
WORKDIR /usr/app/client

# Install Dependencies
COPY package*.json ./
RUN npm ci

# 앱 소스 추가
COPY . .

# Exports
EXPOSE 3000

CMD ["npm", "start"]