version: "3"

services:
  ##########################
  ### SETUP SERVER CONTAINER
  ##########################
  server:
    container_name: kiwe-server
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    ports:
      - "8080:8080"
    env_file: ./server/.env
    environment:
      NODE_ENV: production
    restart: always

  ##########################
  ### SETUP CLIENT(NGINX) CONTAINER
  ##########################
  client:
    container_name: kiwe-nginx
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
      - "443:443"
    links:
      - server
    restart: always
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/usr/share/nginx/html
    # nginx가 매 6시간 설정과 인증서를 백그라운드에서 리로드하고, nginx를 포그라운드에서 런치
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
  ##########################
  ### SETUP CERTBOT CONTAINER
  ##########################
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/usr/share/nginx/html
    # 매 12시간마다 인증서가 갱신 대상인지 확인
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
