version: "3"

services:
  ##########################
  ### SETUP SERVER CONTAINER
  ##########################
  server:
    container_name: kiwe-server
    restart: unless-stopped
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    env_file: ./server/.env
    ports:
      - 3000:3000
    environment:
      NODE_ENV: production
  ##########################
  ### SETUP CLIENT(NGINX) CONTAINER
  ##########################
  nginx:
    restart: unless-stopped
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    env_file: ./client/.env
    ports:
      - 80:80
      - 443:443
    depends_on:
      - server
    volumes:
      - ./client/nginx:/etc/nginx/conf.d
      - ./client/certbot/conf:/etc/letsencrypt
      - ./client/certbot/www:/var/www/certbot
    environment:
      NODE_ENV: production
  ##########################
  ### SETUP CERTBOT CONTAINER
  ##########################
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./client/certbot/conf:/etc/letsencrypt
      - ./client/certbot/www:/var/www/certbot
    # 매 12시간마다 인증서가 갱신 대상인지 확인
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"