// TYPE만 관리하는 곳
export const SAVE_MESSAGE = "SAVE_MESSAGE";
export const LOGIN_USER = "LOGIN_USER";
export const REGISTER_USER = "REGISTER_USER";
export const AUTH_USER = "AUTH_USER";
export const EDIT_PROFILE = "EDIT_PROFILE";

// 여기서부터는 편의성 옵션만을 관리하는 타입
export const EDIT_CONVENIENCE_FONTSIZE = "EDIT_CONVENIENCE_FONTSIZE";
export const EDIT_CONVENIENCE_HIGHCONTRAST = "EDIT_CONVENIENCE_HIGHCONTRAST";
export const EDIT_CONVENIENCE_READMESSAGE = "EDIT_CONVENIENCE_READMESSAGE";
export const EDIT_CONVENIENCE_CHIME = "EDIT_CONVENIENCE_CHIME";