# PRODUCTION BUILD
# Stage 1: Build Server
FROM node:lts-alpine

# Install dependencies
RUN mkdir -p /usr/app/server
WORKDIR /usr/app/server

COPY package*.json ./
RUN npm ci

# copy local files to app folder
COPY . .

ENV PORT 3000
EXPOSE 3000

CMD ["node", "index.js"]