name: KIWE CI/CD
on:
  push:
    branches:
      - dev
      - master
  pull_request:
    branches:
      - dev
      - master

jobs:
  CI:
    runs-on: ubuntu-latest
    # Server, Client 폴더 내에 node_modules가 따로 있으므로 매트릭스로 각자 실행
    strategy:
      matrix: { dir: ["./server", "./client"] }
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup node environment
        uses: actions/setup-node@v2
        with:
          node-version: lts/fermium

      - name: -${{ matrix.dir }}- Install dependencies
        working-directory: ${{ matrix.dir }}
        run: npm ci

      - name: -${{ matrix.dir }}- Lint and format code
        working-directory: ${{ matrix.dir }}
        run: npm run style-check
