name: KIWE Production CI/CD
on:
  push:
    branches:
      - master
  pull_request:
    types:
      - closed
    branches:
      - master

jobs:
  CI:
    runs-on: ubuntu-latest
    # strategy:
    #   matrix: { dir: ["./server", "./client"] }
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup node environment
        uses: actions/setup-node@v2
        with:
          node-version: lts/fermium

      - name: SERVER Install dependencies
        working-directory: ./server
        run: npm ci

      - name: CLIENT Install dependencies
        working-directory: ./client
        run: npm ci

      - name: SERVER Lint and format code
        working-directory: ./server
        run: npm run style-check

      - name: CLIENT Lint and format code
        working-directory: ./client
        run: npm run style-check

      - name: SERVER Create .env file
        working-directory: ./server
        run: |
          touch .env
          echo "GOOGLE_PROJECT_ID=${{ secrets.GOOGLE_PROJECT_ID }}" >> .env
          echo "DIALOGFLOW_SESSION_ID=${{ secrets.DIALOGFLOW_SESSION_ID }}" >> .env
          echo "DIALOGFLOW_LANGUAGE_CODE=${{ secrets.DIALOGFLOW_LANGUAGE_CODE }}" >> .env
          echo "GOOGLE_CLIENT_EMAIL=${{ secrets.GOOGLE_CLIENT_EMAIL }}" >> .env
          echo "GOOGLE_PRIVATE_KEY=${{ secrets.GOOGLE_PRIVATE_KEY }}" >> .env
          echo "MONGO_ID=${{ secrets.MONGO_ID }}" >> .env
          echo "MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }}" >> .env
          echo "EMAIL_ADDRESS=${{ secrets.EMAIL_ADDRESS }}" >> .env
          echo "EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}" >> .env
          echo "KAKAO_ADMIN_KEY=${{ secrets.KAKAO_ADMIN_KEY }}" >> .env
        shell: bash

      - name: CLIENT Create .env file
        working-directory: ./client
        run: |
          touch .env
          echo "REACT_APP_KAKAO_MAP_KEY=${{ secrets.REACT_APP_KAKAO_MAP_KEY }}" >> .env
        shell: bash

      - name: SERVER Test
        working-directory: ./server
        run: npm run test
